version: '3'

tasks:
  "client:build":
    desc: Build the client Docker image using Docker Compose
    cmds:
      - docker compose build client
  
  "client:sh":
    desc: Run the client Docker container using Docker Compose and open a shell
    cmds:
      - docker compose run --rm -it client /bin/sh
    interactive: true

  "client:up":
    desc: Start the client service using Docker Compose in detached mode
    cmds:
      - docker compose up client
  
  "dc":
    desc: Run Docker Compose commands
    cmds:
      - docker compose {{.CLI_ARGS}}
    interactive: true
  
  "dj":
    desc: Run Django management commands in the server container
    cmds:
      - docker compose run --rm server python manage.py {{.CLI_ARGS}}
    interactive: true

  "server:build":
    desc: Build the server Docker image using Docker Compose
    cmds:
      - docker compose build server

  "server:makemigrations":
    desc: Run Django makemigrations in the server container
    cmds:
      - docker compose run --rm server python manage.py makemigrations

  "server:migrate":
    desc: Run Django migrations in the server container
    cmds:
      - docker compose run --rm server python manage.py migrate

  "server:sh":
    desc: Run the server Docker container using Docker Compose and SSH into it
    cmds:
      - docker compose run --rm -it server /bin/sh
  
  "server:test":
    desc: Run Django tests in the server container
    cmds:
      - docker compose run --rm server python manage.py test {{.CLI_ARGS}}
      
  "server:up":
    desc: Start the server service using Docker Compose in detached mode
    cmds:
      - docker compose up server

  "up":
    desc: Start all services using Docker Compose in detached mode
    cmds:
      - docker compose up