# Generated by Django 5.2.3 on 2025-06-20 15:18

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='code_name',
            field=models.CharField(blank=True, max_length=30, validators=[django.core.validators.RegexValidator(code='invalid_code_name', message='Code name must be alphanumeric or contain underscores, dots, or hyphens.', regex='^[a-zA-Z0-9_.-]*$')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, max_length=30, validators=[django.core.validators.RegexValidator(code='invalid_name', message='Name must be alphanumeric or contain underscores, dots, or hyphens.', regex='^[a-zA-Z ]*$')]),
        ),
        migrations.CreateModel(
            name='Ping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('parent_ping', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_pings', to='api.ping')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
