# Generated by Django 5.2.3 on 2025-06-20 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_user_code_name_alter_user_name_ping'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='ping',
            index=models.Index(fields=['user'], name='api_ping_user_id_e5a01c_idx'),
        ),
        migrations.AddIndex(
            model_name='ping',
            index=models.Index(fields=['timestamp'], name='api_ping_timesta_318bcf_idx'),
        ),
        migrations.AddIndex(
            model_name='ping',
            index=models.Index(fields=['latitude', 'longitude'], name='api_ping_latitud_abbaf9_idx'),
        ),
        migrations.AddIndex(
            model_name='ping',
            index=models.Index(fields=['parent_ping'], name='api_ping_parent__53c4b0_idx'),
        ),
    ]
