# Generated by Django 5.2.3 on 2025-07-16 14:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='code_name',
            field=models.CharField(blank=True, error_messages={'unique': 'A user with that code name already exists.'}, max_length=30, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_code_name', message='Code name must be alphanumeric or contain underscores, dots, or hyphens.', regex='^[a-zA-Z0-9_.-]*$')]),
        ),
    ]
